plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id "com.google.devtools.ksp"
    id "com.google.dagger.hilt.android"
}

android {
    namespace "br.com.alura.ceep"
    buildToolsVersion "35.0.0"
    compileSdk 35

    defaultConfig {
        applicationId "br.com.alura.ceep"
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName "1.0"

        ksp {
            arg("room.schemaLocation", "$projectDir/schemas".toString())
        }

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    kotlinOptions {
        jvmTarget = '11'
    }

    buildFeatures {
        viewBinding true
    }
}

hilt {
    enableAggregatingTask = true
}

dependencies {

    def room_version = "2.7.1"
    def lifecycle_version = "2.8.7"

    implementation "androidx.room:room-ktx:$room_version"
    ksp "androidx.room:room-compiler:$room_version"

    implementation "androidx.lifecycle:lifecycle-runtime-ktx:$lifecycle_version"

    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.10.2'
    implementation "io.coil-kt:coil:1.4.0"

    implementation "com.fasterxml.jackson.module:jackson-module-kotlin:2.17.0"
    implementation 'com.squareup.retrofit2:retrofit:2.11.0'
    implementation 'com.squareup.retrofit2:converter-jackson:2.11.0'
    implementation 'androidx.core:core-ktx:1.16.0'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation "com.google.dagger:hilt-android:2.56.1"
    ksp "com.google.dagger:hilt-compiler:2.56.1"
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'
}